# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hood',
        ),
        migrations.RemoveField(
            model_name='review',
            name='judge',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
